package com.aws.a.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="person")
public class Person {
        @DynamoDBHashKey(attributeName="aadharid")
        @DynamoDBAutoGeneratedKey
        private  String aadharid;
        @DynamoDBAttribute
        private String person_name;
        @DynamoDBAttribute
        private String gender;
        @DynamoDBAttribute
        private int age;
        @DynamoDBAttribute
        private int phone;
        public String getAadharid() {
			return aadharid;
		}
		public void setAadharid(String aadharid) {
			this.aadharid = aadharid;
		}
		public String getPerson_name() {
			return person_name;
		}
		public void setPerson_name(String person_name) {
			this.person_name = person_name;
		}
		public String getGender() {
			return gender;
		}
		public void setGender(String gender) {
			this.gender = gender;
		}
		public int getAge() {
			return age;
		}
		public void setAge(int age) {
			this.age = age;
		}
		public int getPhone() {
			return phone;
		}
		public void setPhone(int phone) {
			this.phone = phone;
		}
		public String getCity() {
			return city;
		}
		public void setCity(String city) {
			this.city = city;
		}
		public person_insurance getPerson_insurance() {
			return person_insurance;
		}
		public void setPerson_insurance(person_insurance person_insurance) {
			this.person_insurance = person_insurance;
		}
		@DynamoDBAttribute
        private String city;
        @DynamoDBAttribute
        private person_insurance person_insurance;
        
        
        

}
